env:
  global:
    - secure: TO8Ue6yjC/LRR52WK8YiAQwPSCzRHMIdBnrzCApCyOKJPmE75dw/pxSuEznmqmGAOFpiqwoKXISiMYCeh3zqEk92YAVqHOS/G+7cL9Bp04hDo/B7dhp3XFPNfKhxB9BECmJWRHu9HQOUjZ7Mw47hNXkV+Lgjpw1MR9aC0Z8cq/0Jo0zBL49/8tnubegy1q97PsqR6baAqzpcE+pxy/FW1gImSYfxm8GZ04UF3FBhYm/5IHcPMXEwNUEGUSvn/THL0Z+gLrlM5yRXqFPqqa45S+BEkpkj1uUB78JAabo1RAYKCfWBuE1CgUzIWc4Mjwx9TuzWCFRGkaYxxwzgiK+JHVAhBaZrn7dQQeQAnKhFkZtJNC8Y4eJncWKKi6NYRUYa2YEwxc3gNv3n1d/cXwgtDbwBizzGSVZ8QDTxksNDDyr3v5z6VRdJMevmsilzK8xh/clbCsW+szzIW8AGczF+ofe8dnEzIiAp3sFfSMO1Sx+PPMWVQiTEPlplXuoASnUYByN6VbQFsuEwLjTUu9EF80zj+rGAOxzf6NH+dx5M67Y7cbWX6JzKg1jot/ayNKfwiTxUIC6JM9OFVXY2yuM3/ZB0R4hxelHlCgIZXUwud864Kl2F6XKvbkKtn3u2h+Df8lPIhvue32n/RgRFqRabFjQNF7OKJ0cWM2q4Ofiymh4=
    - RUST_BACKTRACE=1
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
cache: cargo
script:
  - cargo run --release
